def P(name, cat, seg=None, stage=None, cond=lambda r: True, why=""):
    return dict(name=name, cat=cat, seg=seg, stage=stage, cond=cond, why=why)


PRODUCTS = [
    P("Regular Savings Account", "savings", seg=["Mass"],
      why="Simple account to start building a safety balance"),
    P("iWish Goal-Based RD", "savings", seg=["Mass", "Emerging Affluent"],
      cond=lambda r: r["age"] < 50, why="Small monthly deposits toward a specific goal"),
    P("Privilege Banking", "savings", seg=["Affluent", "HNI"],
      why="Priority service and relationship-based pricing"),
    P("Fixed Deposit", "investment",
      cond=lambda r: r["balance_inr"] > 10000 and r["risk_profile"] == "Conservative",
      why="Assured returns with capital safety"),
    P("Mutual Fund SIP", "investment",
      cond=lambda r: r["balance_inr"] > 500 and r["risk_profile"] != "Conservative"
      and r["investment_score"] >= 30,
      why="Disciplined long-term wealth building from small monthly amounts"),
    P("ICICI Pru Life Insurance", "investment", stage=["Young Adult", "Early Career"],
      why="Early start on protection plus savings"),
    P("NPS (National Pension System)", "investment", stage=["Mid Career", "Pre-Retirement"],
      why="Retirement corpus with tax benefits"),
    P("Senior Citizens Savings Scheme", "investment", stage=["Senior"],
      why="Government-backed regular income for seniors"),
    P("Health Insurance", "insurance",
      why="Protects savings from medical emergencies"),
    P("Term Life Insurance", "insurance", stage=["Young Adult", "Early Career", "Mid Career"],
      cond=lambda r: r["employed"], why="High cover at low premium for dependents"),
    P("Motor Insurance", "insurance", cond=lambda r: bool(r.get("has_vehicle")),
      why="Mandatory and covers vehicle damage and liability"),
    P("Personal Loan", "loans",
      cond=lambda r: r["loan_eligible"] and r["employed"] and r["loan"] == "no",
      why="Quick funds with no existing personal loan burden"),
    P("Home Loan", "loans",
      cond=lambda r: 25 <= r["age"] <= 55 and r["loan_eligible"] and r["employed"]
      and r["housing"] == "no", why="No current housing loan and within ideal age window"),
    P("Car Loan", "loans",
      cond=lambda r: r["age"] >= 21 and r["loan_eligible"] and r["employed"],
      why="Eligible on income and clean credit record"),
    P("Gold Loan", "loans", seg=["Mass"],
      why="Fast approval for short-term liquidity needs"),
    P("Amazon Pay ICICI Credit Card", "cards", seg=["Mass", "Emerging Affluent"],
      cond=lambda r: r["default"] == "no", why="No-fee entry card with everyday cashback"),
    P("ICICI Coral Credit Card", "cards", seg=["Emerging Affluent"],
      cond=lambda r: r["default"] == "no", why="Rewards and lifestyle benefits for growing spenders"),
    P("ICICI Sapphiro Credit Card", "cards", seg=["Affluent", "HNI"],
      cond=lambda r: r["default"] == "no", why="Premium rewards, lounge access"),
    P("ICICI Emeralde Credit Card", "cards", seg=["HNI"],
      cond=lambda r: r["default"] == "no", why="Top-tier travel and concierge benefits"),
]